#!/usr/bin/env bash

docker run -d \
  --name etcd \
  -p 2379:2379 \
  -p 2380:2380 \
  --volume=/tmp/etcd-data:/etcd-data \
  quay.io/coreos/etcd:v3.2.1 \
  /usr/local/bin/etcd \
  --name my-etcd-1 \
  --data-dir /etcd-data \
  --listen-client-urls http://localhost:2379 \
  --advertise-client-urls http://localhost:2379 \
  --listen-peer-urls http://localhost:2380 \
  --initial-advertise-peer-urls http://localhost:2380 \
  --initial-cluster my-etcd-1=http://localhost:2380 \
  --initial-cluster-token my-etcd-token \
  --initial-cluster-state new \
  --auto-compaction-retention 1
