#!/usr/bin/env bash

export NODE1=0.0.0.0 

docker run -d \
  -p 2379:2379 \
  -p 2380:2380 \
  --name etcd \
  --network msm \
  quay.io/coreos/etcd:v3.2.1 \
  /usr/local/bin/etcd \
  --data-dir=/etcd-data \
  --name node1 \
  --initial-advertise-peer-urls http://${NODE1}:2380 \
  --listen-peer-urls http://${NODE1}:2380 \
  --advertise-client-urls http://${NODE1}:2379 \
  --listen-client-urls http://${NODE1}:2379 \
  --initial-cluster node1=http://${NODE1}:2380
